DROP TABLE CASE_TABLE IF EXISTS;

CREATE TABLE CASE_TABLE (
    CASE_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EYE_COLOR VARCHAR(20),
    HAIR_COLOR VARCHAR(20)
);